### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by cwilliams5** [ptejada/uFlex#38]
I've made some improvements to the security of uFlex, both in the core files and the demo:
- filtering get/post arrays
- timeout session after X minutes of inactivity
- recaptcha for login/register/forgot password
- switching to PHP's password_hash and password_verify for password storage
- password complexity (min length, cant contain username, compare to list of common pass, require upper/numeric/symbol)

A lot of it is just jammed in for my use, but I could clean some of it up and PR it if you were at all interested.

For most of them we would want them to be opt-in, for example changing hash methods would obviously invalidate all passwords in an upgraded DB. I suppose the best place to put these options would be config.php. Only thing is I'm new to OOP so I'm not sure the best way to store the options and don't want to mess up your coding style.

**Comment by ptejada** [comment]
@cwilliams5 
I agree with most of the suggested improvements. Can you create a new branch with changes so i can review them, ideally all squashed in one commit.

A few notes on points you bring up:
- The filtering of the post arrays is more of an improvement for the demo
- Recaptcha is also an improvement to the demo since it involves the front-end
- For the password complexity is developer defined

I have made changes to the password hashing algorithm before, the key is to passively migrate old hashes to new hashes as users login. Since in the README i mistakenly suggest using the version `1.*` for composer, such a change will require a bump up to version `2.0`.
